package cn.linc.cxf.interfaces;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.1
 * 2017-12-07T16:04:08.366+08:00
 * Generated source version: 2.6.1
 * 
 */
@WebService(targetNamespace = "http://interfaces.cxf.linc.cn/", name = "ServiceUI")
@XmlSeeAlso({ObjectFactory.class})
public interface ServiceUI {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://interfaces.cxf.linc.cn/", className = "cn.linc.cxf.interfaces.SayHello")
    @WebMethod
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://interfaces.cxf.linc.cn/", className = "cn.linc.cxf.interfaces.SayHelloResponse")
    public java.lang.String sayHello(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "fingCarsByUser", targetNamespace = "http://interfaces.cxf.linc.cn/", className = "cn.linc.cxf.interfaces.FingCarsByUser")
    @WebMethod
    @ResponseWrapper(localName = "fingCarsByUserResponse", targetNamespace = "http://interfaces.cxf.linc.cn/", className = "cn.linc.cxf.interfaces.FingCarsByUserResponse")
    public java.util.List<cn.linc.cxf.interfaces.Car> fingCarsByUser(
        @WebParam(name = "arg0", targetNamespace = "")
        cn.linc.cxf.interfaces.User arg0
    );
}
